name: CI

on:
  push:
    paths:
      - '*.c'
      - '*.h'
      - 'Makefile'
      - '.github/workflows/*'
  pull_request:
    paths:
      - '*.c'
      - '*.h'
      - 'Makefile'
      - '.github/workflows/*'
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  build:
    name: Build
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            arch: x86_64
          - os: ubuntu-24.04-arm
            arch: aarch64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: make STATIC=1

      - name: Strip
        if: ${{ github.event_name == 'release' }}
        run: strip tdp

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tdp-${{ matrix.arch }}
          path: tdp

      - name: Upload artifact to release
        if: ${{ github.event_name == 'release' }}
        uses: svenstaro/upload-release-action@v2
        with:
          file: tdp
          asset_name: tdp-${{ matrix.arch }}
