name: CI

on:
  push:
    paths:
      - '*.c'
      - '*.h'
      - 'Makefile'
      - '.github/workflows/*'
  pull_request:
    paths:
      - '*.c'
      - '*.h'
      - 'Makefile'
      - '.github/workflows/*'
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  build:
    name: Build
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            arch: x86_64
          - os: ubuntu-24.04-arm
            arch: aarch64
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: make STATIC=1 BIN=tdp-${{ matrix.arch }}

      - name: Strip
        if: ${{ github.event_name == 'release' }}
        run: strip tdp-${{ matrix.arch }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tdp-${{ matrix.arch }}
          path: tdp

      - name: Upload artifact to release
        if: ${{ github.event_name == 'release' }}
        uses: softprops/action-gh-release@v2
        with:
          files: tdp-${{ matrix.arch}}
